-- Script para la tabla de Colaboradores de Carley Interactive Studio

-- 1. Tabla de Colaboradores
CREATE TABLE public.collaborators (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  photo_url TEXT,
  collaboration_details TEXT NOT NULL,
  type TEXT DEFAULT 'General', -- Opcional: Para categorizar la colaboración
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Seguridad (Row Level Security - RLS)
ALTER TABLE public.collaborators ENABLE ROW LEVEL SECURITY;

-- Políticas: Cualquiera puede ver los colaboradores, pero solo admins (o nadie vía web por ahora) pueden insertar.
CREATE POLICY "Cualquiera puede ver colaboradores" ON public.collaborators FOR SELECT USING (true);
CREATE POLICY "Solo inserción por admins" ON public.collaborators FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Solo actualización por admins" ON public.collaborators FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Solo borrado por admins" ON public.collaborators FOR DELETE USING (auth.role() = 'service_role');
