-- Setup Script: Crea la base de datos para Carley Interactive Studio
-- Ejecuta esto en el Editor SQL de Supabase

-- 1. Perfiles de Usuario (Extensión de Auth.Users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT,
  avatar_url TEXT,
  gender TEXT,
  usage_type TEXT,
  institution TEXT,
  language TEXT DEFAULT 'es',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Opiniones / Reviews
CREATE TABLE public.opinions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  user_email TEXT,
  product_id TEXT NOT NULL, -- 'CE' (Creative Engine) o 'VS' (Vid Spri)
  content TEXT NOT NULL,
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Reportes de Bugs
CREATE TABLE public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT,
  message TEXT NOT NULL,
  photos_urls TEXT[], -- Array de enlaces a imágenes
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Reclamaciones
CREATE TABLE public.claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT,
  reason TEXT NOT NULL,
  photo_url TEXT,
  status TEXT DEFAULT 'pending', -- 'pending', 'resolved', 'refunded'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Donaciones (Registro Público)
CREATE TABLE public.donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_name TEXT DEFAULT 'Anónimo',
  amount DECIMAL(10,2) NOT NULL,
  product_id TEXT NOT NULL, -- 'CE' o 'VS'
  paypal_order_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- SEGURIDAD (Row Level Security - RLS)
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opinions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;

-- Políticas de Perfiles
CREATE POLICY "Cualquiera puede ver perfiles públicos" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Usuarios pueden actualizar su propio perfil" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Políticas de Opiniones
CREATE POLICY "Cualquiera puede ver opiniones" ON public.opinions FOR SELECT USING (true);
CREATE POLICY "Usuarios autenticados pueden crear opiniones" ON public.opinions FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Políticas de Reportes/Reclamos (Privados)
CREATE POLICY "Cualquiera puede enviar reportes" ON public.reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Cualquiera puede enviar reclamos" ON public.claims FOR INSERT WITH CHECK (true);

-- Políticas de Donaciones
CREATE POLICY "Donaciones visibles para todos" ON public.donations FOR SELECT USING (true);
CREATE POLICY "Insertar donaciones (público para PayPal callback)" ON public.donations FOR INSERT WITH CHECK (true);

-- ==========================================
-- AUTOMATIZACIÓN (Triggers)
-- ==========================================

-- Función para crear perfil automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url, gender, usage_type, institution, language)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'username',
    NEW.raw_user_meta_data->>'avatar_url',
    NEW.raw_user_meta_data->>'gender',
    NEW.raw_user_meta_data->>'usage_type',
    NEW.raw_user_meta_data->>'institution',
    COALESCE(NEW.raw_user_meta_data->>'language', 'es')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger disparado tras el registro en auth.users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
