    es: {
        welcome: "Bienvenido, nos alegra tenerte aquí",
        "btn-yes": "Sí",
        "btn-no": "No",
        "search-ph": "Buscar en Carley...",
        "hero-desc": "¿Has pensado alguna vez en desarrollar tu propio videojuego? Pues bien, hemos diseñado Creative Engine para ti, un motor de videojuegos en 2D que lo facilita todo. No importa si tienes experiencia en la creación de juegos o no, Creative Engine está hecho para ti. Cualquier idea que tengas, Creative Engine te ayuda a hacerla realidad.",
        "hero-cta": "Empezar a crear",
        "creative-games-desc": "Juega sin descargar nada, diviértete en la web. Juega a todos los juegos hechos con Creative Engine, ya sea para PC, consola o móvil.",
        "btn-visit": "Visitar",
        "vidspri-home-desc": "Crea animaciones a partir de vídeos para tus juegos. Genera un vídeo en cualquier página y nuestra herramienta lo convierte en una hoja de sprites para tus videojuegos.",
        "carl-ia-desc": "Nuestra IA actualmente en desarrollo. Muy pronto estará disponible para ayudarte en todo lo que necesites. Nuestro modelo será completo: tendrá visión, podrá hablar, generar texto y escuchar. Lo estamos entrenando para ser el compañero integral definitivo.",
        "learn-more": "Saber más",
        "traspilador-desc": "Diseñado para desarrolladores. Un modelo de codificación capaz de convertir proyectos de un lenguaje a otro (ejemplo: de JS a C++). Simplifica la migración de tus proyectos y acelera tu flujo de trabajo.",
        "explore-docs": "Explorar documentación",
        "btn-save": "Guardar Cambios",
        "btn-go-donate-page": "Ir a Donaciones",
        "btn-confirm-delete": "Eliminar Permanentemente",
        "footer-channels": "Canales",
        "footer-donations": "Donaciones",
        "footer-info": "Información",
        "footer-products": "Nuestros Productos",
        "footer-available": "Disponibles",
        "footer-not-available": "No Disponibles",
        "acc-modal-title": "Mi Cuenta",
        "field-email": "Correo Electrónico",
        "field-username": "Nombre de Usuario",
        "btn-update": "Actualizar Perfil",
        "btn-logout": "Cerrar Sesión",
        "modal-hint": "Inicia sesión para gestionar tus proyectos.",
        "btn-login": "Entrar",
        "btn-register": "Crear Cuenta",
        "login-title": "Entrar",
        "ph-email": "Correo Electrónico",
        "ph-pass": "Contraseña",
        "ph-pass-confirm": "Confirmar Contraseña",
        "btn-login-action": "Entrar",
        "register-title": "Crear Cuenta",
        "ph-reg-user": "Nombre de Usuario",
        "ph-reg-email": "Correo Electrónico",
        "ph-reg-pass": "Contraseña",
        "ph-reg-pass-confirm": "Confirmar Contraseña",
        "btn-reg-action": "Registrarse",
        "btn-delete-acc": "Eliminar Cuenta",
        "ce-nav-info": "Información",
        "ce-nav-tutorials": "Tutoriales",
        "ce-nav-collabs": "Colaboradores",
        "ce-nav-solutions": "Soluciones Rápidas",
        "ce-nav-docs": "Documentación",
        "ce-nav-docs-leyes": "Componentes",
        "ce-nav-docs-scripting": "Scripting CES",
        "ce-nav-docs-libs": "Librerías",
        "ce-nav-docs-carl": "Carl IA",
        "ce-nav-docs-terminal": "Terminal",
        "ce-nav-docs-editors": "Editores",
        "ce-nav-docs-advanced": "Avanzado",
        "ce-nav-docs-config": "Configuración",
        "ce-docs-leyes-title": "Guía de Componentes (Leyes) - Creative Engine",
        "ce-docs-leyes-intro": "En Creative Engine, las **Materias** (objetos) cobran vida a través de las **Leyes** (componentes). Cada Ley añade una funcionalidad específica, como gravedad, renderizado de imagen o lógica de IA.",
        "ce-docs-leyes-inspector": "Uso en Inspector:",
        "ce-docs-leyes-scripting": "Scripting:",
        "ce-docs-core-title": "1. Componentes Base (Core)",
        "ce-docs-transform-name": "Transform (Transformación)",
        "ce-docs-transform-desc": "Define la posición, rotación y escala de un objeto en el espacio 2D.",
        "ce-docs-transform-inspector": "Uso en Inspector: Edita los valores X e Y para mover el objeto. Usa los botones de volteo (Flip) para invertir la imagen.",
        "ce-docs-camera-name": "Camera (Cámara)",
        "ce-docs-camera-desc": "Define el área visible del juego.",
        "ce-docs-camera-inspector": "Uso en Inspector: Configura el color de fondo, el zoom y la máscara de capas (Culling Mask) para decidir qué objetos ve esta cámara.",
        "ce-docs-render-title": "2. Renderizado y Visuales",
        "ce-docs-sprite-name": "SpriteRenderer (Renderizador de Sprite)",
        "ce-docs-sprite-desc": "Muestra una imagen (.png, .jpg) o un cuadro de una hoja de sprites (.ceSprite).",
        "ce-docs-sprite-inspector": "Uso en Inspector: Arrastra una imagen al campo \"Source\". Puedes cambiar el color para tintar la imagen o ajustar la opacidad.",
        "ce-docs-water-name": "Water (Agua)",
        "ce-docs-water-desc": "Simulación física de fluidos basada en partículas.",
        "ce-docs-water-inspector": "Uso en Inspector: Define el ancho y alto del área de agua. Ajusta la densidad (flotación) y viscosidad.",
        "ce-docs-video-name": "VideoPlayer (Reproductor de Video)",
        "ce-docs-video-desc": "Reproduce archivos de video en el mundo o en la UI.",
        "ce-docs-video-inspector": "Uso en Inspector: Soporta formatos .mp4 y .webm. Puedes activar el bucle (loop) y ajustar el volumen.",
        "ce-docs-physics-title": "3. Físicas 2D",
        "ce-docs-rigidbody-name": "Rigidbody2D (Física)",
        "ce-docs-rigidbody-desc": "Permite que el objeto reaccione a la gravedad y colisiones.",
        "ce-docs-rigidbody-inspector": "Uso en Inspector: Cambia el tipo de cuerpo a \"Dynamic\" para que caiga, o \"Kinematic\" para moverlo manualmente pero que detecte colisiones.",
        "ce-docs-collider-name": "BoxCollider2D / CircleCollider2D (Colisionadores)",
        "ce-docs-collider-desc": "Definen la forma física para los choques.",
        "ce-docs-collider-inspector": "Uso en Inspector: Ajusta el tamaño o radio. Si marcas \"Is Trigger\", el objeto no chocará pero detectará cuando algo entre en su área.",
        "ce-docs-ai-title": "4. Inteligencia y Movimiento",
        "ce-docs-basicai-name": "BasicAI (IA Básica)",
        "ce-docs-basicai-desc": "Comportamientos automáticos para NPCs y enemigos.",
        "ce-docs-basicai-modes": "Modos: Follow (Sigue a una Materia), Escape (Huye de un objetivo), Wander (Camina aleatoriamente).",
        "ce-docs-patrol-name": "Patrol (Patrulla)",
        "ce-docs-patrol-desc": "Mueve el objeto entre dos puntos.",
        "ce-docs-ui-title": "5. Interfaz de Usuario (UI)",
        "ce-docs-canvas-name": "Canvas (Lienzo)",
        "ce-docs-canvas-desc": "El contenedor principal para todos los elementos de interfaz.",
        "ce-docs-button-name": "Button (Botón)",
        "ce-docs-button-desc": "Detecta clics del usuario.",
        "ce-docs-button-inspector": "Uso en Inspector: Permite definir colores para los estados (Normal, Presionado, Desactivado) o cambiar sprites.",
        "ce-docs-uitext-name": "UIText (Texto UI)",
        "ce-docs-uitext-desc": "Muestra texto en pantalla con fuentes personalizadas.",
        "ce-docs-anim-title": "6. Animación y Audio",
        "ce-docs-animator-name": "AnimatorController (Controlador)",
        "ce-docs-animator-desc": "Gestiona estados de animación (Caminar, Saltar, Quieto).",
        "ce-docs-animator-inspector": "Uso en Inspector: Requiere un archivo .ceanim. El \"Smart Mode\" anima automáticamente según el movimiento.",
        "ce-docs-audio-name": "AudioSource (Fuente de Audio)",
        "ce-docs-audio-desc": "Reproduce efectos de sonido o música.",
        "ce-docs-audio-inspector": "Uso en Inspector: Soporta Audio Espacial (el volumen baja si el objeto se aleja).",
        "ce-docs-others-title": "7. Otros Componentes",
        "ce-docs-others-raycast": "RaycastSource (Rallo): Lanza rayos invisibles para detectar paredes o enemigos.",
        "ce-docs-others-particles": "ParticleSystem (Partículas): Crea efectos de fuego, humo o chispas.",
        "ce-docs-others-parallax": "Parallax: Crea fondos infinitos con profundidad.",
        "ce-docs-others-light": "Light2D (Luces): Ilumina tu escena con luces puntuales o focales.",
        "ce-docs-protip-title": "Pro-Tip de Scripting",
        "ce-docs-protip-desc": "Recuerda que en Creative Engine, puedes acceder a cualquier componente directamente por su nombre en español. No necesitas usar prefijos.",
        "ce-docs-carl-keys": "Configura tu clave en Editar > Preferencias > IA. Soportamos Google Gemini (Gratis), OpenAI y Anthropic.",
        "ce-docs-carl-skill-1": "\"Crea un objeto llamado Jugador con SpriteRenderer.\"",
        "ce-docs-carl-skill-2": "\"Crea un script que mueva al jugador con las flechas.\"",
        "ce-docs-terminal-ls": "ls: Listar archivos.",
        "ce-docs-terminal-cd": "cd <carpeta>: Cambiar de carpeta.",
        "ce-docs-terminal-clear": "clear: Limpiar terminal.",
        "ce-docs-terminal-act-1": "Ventana > Terminal",
        "ce-docs-terminal-act-2": "Panel Inferior > Pestaña Terminal",
        "ce-docs-advanced-struct-1": "/Assets: Imágenes, sonidos, scripts.",
        "ce-docs-advanced-struct-2": "/lib: Librerías (.celib).",
        "ce-docs-advanced-struct-3": "project.ceconfig: Configuración técnica.",
        "ce-docs-advanced-scenes-desc": "Usa Ctrl + S para guardar. Las escenas (.ceScene) contienen todos los objetos y luces.",
        "ce-docs-advanced-build-desc": "Genera un paquete web independiente (.zip) listo para hosting.",
        "ce-docs-editors-sprite-desc": "Recorta imágenes grandes en múltiples sprites pequeños.",
        "ce-docs-editors-anim-desc": "Crea secuencias (.cea) usando una línea de tiempo.",
        "ce-docs-editors-tilemap-desc": "Diseña niveles basados en rejilla con pinceles y capas.",
        "ce-docs-config-project-desc": "Gestiona Sorting Layers, Collision Layers y Tags.",
        "ce-docs-config-ambient-desc": "Ciclo Día/Noche, filtros de color y luces ambientales.",
        "ce-docs-scripting": "Scripting",
        "ce-docs-scripting-title": "Guía Maestra de Scripting (CES)",
        "ce-docs-scripting-intro": "Creative Engine utiliza CES (Creative Engine Script), un lenguaje potente basado en JavaScript pero simplificado para creadores de videojuegos.",
        "ce-docs-scripting-core-title": "Conceptos Fundamentales",
        "ce-docs-scripting-import": "Todo script debe empezar con la instrucción para conectar con el motor: ve motor;",
        "ce-docs-scripting-access": "Acceso Directo: NO necesitas escribir this. o mtr. para acceder a los componentes.",
        "ce-docs-scripting-vars-title": "Variables Públicas (Inspector)",
        "ce-docs-scripting-vars-desc": "Para que una variable aparezca en el Inspector, usa la palabra clave publico.",
        "ce-docs-scripting-events-title": "Eventos de Ciclo de Vida",
        "ce-docs-scripting-input-title": "Entrada (Input) y Movimiento",
        "ce-docs-scripting-example-title": "Ejemplos Prácticos",
        "ce-docs-scripting-functions-title": "Funciones Especiales",
        "ce-docs-libs-title": "Guía de Librerías y Extensibilidad",
        "ce-docs-libs-intro": "Las librerías (.celib) permiten extender tanto la interfaz del editor como las capacidades de programación.",
        "ce-docs-libs-ui-title": "1. Librerías de Interfaz (Herramientas del Editor)",
        "ce-docs-libs-runtime-title": "2. Librerías de Runtime (Nuevas Funciones)",
        "ce-docs-libs-install-title": "Cómo Crear e Instalar una Librería",
        "ce-docs-carl-title": "Guía de Carl IA: Tu Asistente Autónomo",
        "ce-docs-carl-intro": "Carl IA es un agente inteligente capaz de manipular el editor, crear archivos y ayudarte a construir tu juego paso a paso.",
        "ce-docs-carl-activate-title": "Cómo Activar a Carl IA",
        "ce-docs-carl-config-title": "Configuración (API Keys)",
        "ce-docs-carl-skills-title": "Habilidades Autónomas",
        "ce-docs-carl-modes-title": "Modos de Ejecución",
        "ce-docs-carl-modes-desc": "Carl puede trabajar en modo \"Asistente\" (te guía) o \"Autónomo\" (hace los cambios por ti).",
        "ce-why-title": "¿Por qué usar Creative Engine?",
        "ce-why-1": "El motor está en varios idiomas diferentes y tiene 3 formas de codificar:",
        "ce-ces-desc": "Diseñado para quienes ya son expertos en la creación de videojuegos y gustan programar a puro código. Hecho con JS e inspirado en C#, JS y Python. Permite programar completamente en español, inglés, portugués, ruso y chino (y se extenderá a más idiomas).",
        "ce-scratch-desc": "Podrán crear la lógica del juego arrastrando bloques. Muy bueno para quienes están empezando. Aún está en desarrollo.",
        "ce-human-desc": "Aquí solo tendrás que hablarle al motor, decirle lo que quieres que haga el script y el motor te entenderá.",
        "ce-info-3": "Puedes crear un juego en menos de 1 hora y sin escribir ni una sola línea de código. El motor incluye varios componentes básicos que te ayudan a crear tus juegos. Al ser web, puedes publicarlos en varias plataformas y para varios dispositivos.",
        "ce-info-4": "Nuestro motor tiene un sistema de librería que permite a los desarrolladores crear varias librerías. Si quieres, por ejemplo, una IA para tu juego, no tienes que hacer una IA avanzada desde 0; solo descargas la librería y listo.",
        "ce-info-5": "Nuestro motor tiene integrado a Carl IA que te ayudará a hacer realidad tus ideas y te guiará en cada paso de tu desarrollo.",
        "ce-info-free": "Creative Engine es 100% gratuito. No reclamamos derechos por ningún juego hecho con él; de hecho, mientras más creas, más nos alegramos.",
        "ce-info-open": "El motor mismo estará disponible en código abierto para todos aquellos que quieran modificarlo a sus gustos.",
        "ce-info-team": "Creative Engine tiene en desarrollo un sistema que te permitirá crear videojuegos en equipo. Muy bueno para escuelas que quieren enseñar el desarrollo de videojuegos a los estudiantes o pequeños estudios.",
        "ce-info-vidspri": "Creative Engine tiene integrado a Vid Spri, una herramienta que te permite crear animaciones y sonido para tus videojuegos.",
        "ph-bug-desc": "Describe el fallo...",
        "field-message": "Mensaje",
        "field-photos": "Fotos (Máx 5)",
        "btn-send": "Enviar Reporte",
        "field-opinion": "Tu Opinión",
        "ph-opinion": "¿Qué piensas de Creative Engine?",
        "btn-send-opinion": "Publicar Opinión",
        "opinion-hint": "Leeremos sus opiniones y consideraremos todas aquellas con más me gusta en futuras actualizaciones.",
        "ce-license-1": "Los juegos hechos están disponibles bajo la licencia CLG1 (Carley Gratuito).",
        "ce-license-2": "El licenciatario tiene todo derecho de usar como le dé la gana en todo su producto. No reclamamos ningún porcentaje.",
        "ce-license-3": "No somos responsables; o sea, no tenemos una obligación de resolver bugs, fallos o errores que pueda presentar el producto.",
        "ce-license-4": "No tenemos derechos en el producto del usuario a menos que este nos lo permita.",
        "ce-license-date": "Última actualización: 4 de marzo de 2026",
        "ce-privacy-main": "No guardamos ningún otro tipo de datos que no sea información necesaria para su cuenta y opiniones en nuestros servidores, etc.",
        "ce-claim-reason": "Razón del reclamo",
        "claim-hint": "Puedes reclamar en la misma semana que hayas hecho las donaciones; posteriormente no garantizamos una devuelta.",
        "btn-send-claim": "Enviar Reclamo",
        "ce-donate-1": "No necesitas ser un desarrollador para aportar a nuestro motor. Tu apoyo monetario nos ayudará a contratar desarrolladores y pagar servidores para hacer de Vid Spri una herramienta muy útil y gratis.",
        "ce-donate-2": "Nos financiará a seguir adelante y pagar servidores para que en un futuro puedas usar Carl IA sin depender de API externa de forma gratuita.",
        "btn-support": "Apoyar",
        "btn-ad": "Ver un anuncio para apoyarnos",
        "ce-donate-claim": "Si en todo caso quieres hacer un reclamo puedes hacerlo desde Reclamos.",
        "ce-nav-credits": "Créditos",
        "credits-main": "Este proyecto no estaría sin la increíble ayuda de Google Jules, quien ha hecho gran parte del proyecto. Agradecemos a Google por sus generosos planes gratuitos.",
        "credits-ms": "También agradecemos a Microsoft Copilot, que también ha aportado al proyecto significativamente.",
        "credits-gemini": "Finalmente, agradecemos a Google AI Studio por su generoso plan y a su modelo de Gemini para el uso gratuito de Carl IA.",
        "vs-nav-tutorials": "Tutoriales",
        "vs-donate-intro": "Tu apoyo es lo que permite que Vid Spri siga siendo una herramienta gratuita y de libre acceso. Queremos que cada creador tenga las mejores herramientas sin importar su presupuesto, y por ello mantenemos una total transparencia sobre los costos de servidores necesarios para que la IA funcione para ti. Sus donaciones ayudarán a que otros usen nuestras herramientas gratuitamente.",
        "vs-info-1": "VidSpri fue creado pensando en los desarrolladores novatos o aquellos que quieren crear sus videojuegos 2D pero que no tienen experiencia dibujando cada fotograma.",
        "vs-info-2": "A muchos les ha ocurrido acudir a la IA para generar fotogramas para sus personajes, pero la IA tampoco puede hacer bien este trabajo; no sabe cómo hacerlo hasta que nos dimos cuenta de que la IA, al generar video, lo hace mucho mejor que cuando genera una simple imagen con varios sprites.",
        "vs-info-3": "Se nos ocurrió hacer una herramienta que convierte videos a hojas de sprites. Nuestra herramienta saca fotogramas de videos y los convierte en una hoja de sprites o genera un video para sacarle fotogramas, logrando un mejor resultado.",
        "vs-info-4": "Para hacerlo más completo, hemos hecho que pueda generar sonido para tus videojuegos.",
        "vs-credits-main": "Créditos Desarrollo y Asistencia VidSpri es un proyecto de Carley Interactive Studio. Este proyecto fue desarrollado con la asistencia de Jules, un ingeniero de software de IA de Google. Agradecemos a Google por proporcionar acceso a esta increíble herramienta que hizo posible acelerar y mejorar nuestro proceso de desarrollo.",
        "vs-credits-hf": "Agradecimientos Especiales Queremos extender un agradecimiento especial a Hugging Face por proporcionar el alojamiento gratuito para nuestros servidores a través de su plataforma Spaces. Su apoyo a la comunidad de código abierto es lo que permite que herramientas como VidSpri estén disponibles para todos de forma gratuita.",
        "vs-credits-os": "Tecnologías y Librerías de Código Abierto Esta aplicación no sería posible sin el increíble trabajo de la comunidad de código abierto. Agradecemos a los desarrolladores y mantenedores de las siguientes tecnologías y librerías:",
        "donate-big-title": "Tu apoyo vale mucho",
        "donate-intro-msg": "Estás aportando a que otros puedan usar nuestra app y motor de forma gratuita.",
        "transparency-title": "Nuestra Misión",
        "transparency-desc-long": "Queremos que VidSpri sea gratuito para todos, sin modelos freemium ni premium. Queremos que todos tengan el mismo acceso a todas las herramientas para crear animaciones y música. Creative Engine ya es gratuito, y queremos que Carl IA también lo sea, completamente integrado. Para mantener esto, necesitamos cubrir costos de servidores de Hugging Face y Supabase.",
        "support-action-title": "Apoyar proyecto",
        "vs-tutorial-title": "Tutoriales",
        "vs-tutorial-desc": "Aprende a usar Vid Spri para tus proyectos.",
        "vs-donate-1": "No necesitas ser un desarrollador para aportar a nuestro proyecto. Tu apoyo monetario nos ayudará a contratar desarrolladores y pagar servidores para hacer de Vid Spri una herramienta muy útil y gratis.",
        "vs-os-python-desc": "El lenguaje de programación que impulsa todo nuestro backend.",
        "vs-os-docker-desc": "La plataforma de contenedores que nos permite desplegar el servidor de forma fiable.",
        "vs-os-fastapi-desc": "Un moderno y rápido framework web para construir nuestras APIs.",
        "vs-os-uvicorn-desc": "Un servidor ASGI ultrarrápido, utilizado para ejecutar la aplicación de backend.",
        "vs-os-rembg-desc": "La potente librería utilizada para eliminar el fondo de las imágenes de forma inteligente.",
        "vs-os-pillow-desc": "Una librería fundamental para la manipulación de imágenes en Python.",
        "vs-os-onnx-desc": "El motor de inferencia de alto rendimiento que potencia el modelo de rembg.",
        "vs-os-multipart-desc": "Librería esencial para la gestión de subida de archivos en el servidor.",
        "vs-os-sqlite-desc": "El motor de base de datos utilizado para gestionar la cola de procesamiento y los códigos de prioridad.",
        "vs-os-translate-desc": "El servicio que potencia la funcionalidad de traducción en la aplicación.",
        "vs-os-feather-desc": "La librería de iconos de código abierto que proporciona los iconos de la interfaz de usuario.",
        "vs-os-crop-desc": "Una librería de JavaScript para la funcionalidad de recorte de imágenes en el frontend.",
        "acc-100-free": "100% Gratuito",
        "acc-personal-info": "Información Personal",
        "acc-support-simple-desc": "Nuestras aplicaciones son gratuitas gracias a tu apoyo.",
        "support-ce": "Soporte Creative Engine",
        "support-vs": "Soporte Vid Spri",
        "claim-sad-msg": "Lamentamos mucho que haya tenido que llegar a este punto. Tratamos de hacer todo de la mejor forma para que todos puedan disfrutar.",
        "field-claim-photo": "Foto de confirmación de donación",
        "ph-claim-desc": "Explica el motivo...",
        "acc-delete-long-warning": "Esta acción es irreversible. Se enviará un correo de confirmación. Por favor, introduce tu contraseña para proceder.",
        "support-title": "Apoyo para todos",
        "support-intro": "Transparencia absoluta. Aquí puedes ver cómo las apps de Carley se mantienen gratuitas para el mundo.",
        "stat-total-users": "Usuarios Totales",
        "stat-monthly-goal": "Meta Mensual",
        "stat-collected-label": "Recaudado",
        "list-title": "Nuestros Colaboradores",
        "col-name": "Nombre",
        "col-amount": "Aportación",
        "empty-supporters": "Aún no hay aportaciones registradas este mes. ¡Sé el primero!",
        "support-how-to": "¿Quieres aparecer aquí? Apóyanos mediante PayPal en la sección de donaciones de nuestras apps.",
        "btn-go-donate": "Ir a Donar",
    },
    en: {
    en: {
        welcome: "Welcome, we're glad to have you here",
        "btn-yes": "Yes",
        "btn-no": "No",
        "privacy-modal-title": "Privacy and Terms of Use",
        "privacy-modal-desc": "Your privacy is our priority. We do not share your data with third parties or sell it. This unique account will allow you to access all Carley Interactive Studio products and apps. The user is solely responsible for the security of their account and any data they choose to share with third parties. We offer full support for account recovery and access issues. By using our services, you agree that Carley is not responsible for any misuse of the account by the user.",
        "search-ph": "Search in Carley...",
        "hero-desc": "Have you ever thought about developing your own video game? Well, we have designed Creative Engine for you, a 2D video game engine that makes everything easy. Whether you have experience in game creation or not, Creative Engine is made for you. Any idea you have, Creative Engine helps you turn it into reality.",
        "hero-cta": "Start Creating",
        "hero-more": "Learn more",
        "creative-games-desc": "Play without downloading anything, have fun on the web. Play all games made with Creative Engine, whether for PC, console, or mobile.",
        "btn-visit": "Visit",
        "vidspri-home-desc": "Create animations from videos for your games. Generate a video on any page and our tool converts it into a sprite sheet for your video games.",
        "carl-ia-desc": "Our AI currently under development. Very soon it will be available to help you with everything you need. Our model will be complete: it will have vision, be able to speak, generate text, and listen. We are training it to be the ultimate integral companion.",
        "learn-more": "Learn more",
        "traspilador-desc": "Designed for developers. A coding model capable of converting projects from one language to another (example: from JS to C++). Simplify your project migration and speed up your workflow.",
        "explore-docs": "Explore documentation",
        "btn-save": "Save Changes",
        "btn-go-donate-page": "Go to Donations",
        "btn-confirm-delete": "Permanently Delete",
        "footer-channels": "Channels",
        "footer-donations": "Donations",
        "footer-info": "Information",
        "footer-products": "Our Products",
        "footer-available": "Available",
        "footer-not-available": "Not Available",
        "footer-donate-paypal": "Donate with PayPal",
        "footer-donate-info": "What do we do with your donations?",
        "footer-see-donors": "See donors",
        "footer-see-collabs": "Collaborators",
        "footer-privacy": "Privacy Policy",
        "footer-license": "License",
        "footer-copyright": "© 2026 Carley Interactive Studio. All rights reserved.",
        "acc-modal-title": "My Account",
        "acc-page-title": "Welcome to Carley Studio",
        "btn-recovery": "Recover",
        "field-recovery-email": "Recovery Email",
        "field-gender": "Gender",
        "gender-m": "Male",
        "gender-f": "Female",
        "field-language": "Language",
        "acc-global-notice": "This account will serve you for all our products and Carley apps.",
        "acc-terms-accept": "I accept the conditions and",
        "recovery-desc": "Enter your email to receive recovery instructions.",
        "btn-recovery-action": "Send Instructions",
        "btn-back-home": "Back to Home",
        "acc-profile-title": "My Account",
        "field-email": "Email",
        "field-username": "Username",
        "field-pfp": "Profile Picture (URL .png/.jpg)",
        "field-usage": "Account usage",
        "usage-personal": "Personal",
        "usage-edu": "Educational",
        "usage-biz": "Small Business",
        "field-institution": "School / Studio name",
        "acc-change-pass": "Change Password",
        "acc-support-title": "Support for everyone",
        "acc-support-desc": "We keep our apps free thanks to collaboration. Cost increases with users.",
        "btn-see-support": "See Contributors",
        "acc-delete-title": "Danger Zone",
        "acc-delete-warning": "This action is irreversible. All your data will be deleted.",
        "btn-delete-acc": "Delete Account",
        "btn-update": "Update Profile",
        "btn-logout": "Log Out",
        "acc-personal-info": "Personal Information",
        "acc-support-simple-desc": "Our applications are free thanks to your support.",
        "acc-100-free": "100% Free",
        "support-ce": "Support Creative Engine",
        "support-vs": "Support Vid Spri",
        "claim-sad-msg": "We are very sorry that it has come to this. We try to do everything in the best way so that everyone can enjoy.",
        "field-claim-photo": "Donation confirmation photo",
        "ph-claim-desc": "Explain the reason...",
        "acc-delete-long-warning": "This action is irreversible. A confirmation email will be sent. Please enter your password to proceed.",
        "modal-hint": "Log in to manage your projects.",
        "btn-login": "Enter",
        "btn-register": "Create Account",
        "login-title": "Log In",
        "ph-email": "Email",
        "ph-pass": "Password",
        "ph-pass-confirm": "Confirm Password",
        "btn-login-action": "Enter",
        "register-title": "Create Account",
        "btn-register-action": "Register",
        "donations-modal-title": "What do we do with your donations?",
        "donations-modal-desc": "Your support allows us to hire more talent, improve our servers, and accelerate the development of free tools for the community like Creative Engine. Every donation is invested directly into improving our technologies.",
        "license-modal-title": "License",
        "license-modal-desc": "All our products are protected by international intellectual property laws.",
        // Creative Engine
        "ce-nav-info": "Information",
        "ce-nav-report": "Report",
        "ce-nav-opinions": "Opinions",
        "ce-nav-license": "License",
        "ce-nav-privacy": "Privacy",
        "ce-nav-join": "Join & Follow",
        "ce-nav-claims": "Claims",
        "ce-nav-donations": "Donations",
        "ce-nav-collabs": "Collaborators",
        "ce-nav-solutions": "Quick Solutions",
        "ce-nav-docs": "Documentation",
        "ce-nav-docs-leyes": "Components",
        "ce-nav-docs-scripting": "Scripting CES",
        "ce-nav-docs-libs": "Libraries",
        "ce-nav-docs-carl": "Carl IA",
        "ce-nav-docs-terminal": "Terminal",
        "ce-nav-docs-editors": "Editors",
        "ce-nav-docs-advanced": "Advanced",
        "ce-nav-docs-config": "Configuration",
        "ce-docs-leyes-title": "Component Guide (Leyes) - Creative Engine",
        "ce-docs-leyes-intro": "In Creative Engine, **Matters** (objects) come to life through **Leyes** (components). Each Ley adds specific functionality, such as gravity, image rendering, or AI logic.",
        "ce-docs-leyes-inspector": "Inspector Usage:",
        "ce-docs-leyes-scripting": "Scripting:",
        "ce-docs-core-title": "1. Core Components",
        "ce-docs-transform-title": "Transform",
        "ce-docs-transform-desc": "Defines the position, rotation, and scale of an object in 2D space.",
        "ce-docs-transform-ins": "Edit X and Y values to move the object. Use the Flip buttons to invert the image.",
        "ce-docs-camera-title": "Camera",
        "ce-docs-camera-desc": "Defines the visible area of the game.",
        "ce-docs-camera-ins": "Configure background color, zoom, and Culling Mask.",
        "ce-docs-render-title": "2. Rendering and Visuals",
        "ce-docs-sprite-title": "SpriteRenderer",
        "ce-docs-sprite-desc": "Displays an image (.png, .jpg) or a frame from a sprite sheet (.ceSprite).",
        "ce-docs-sprite-ins": "Drag an image to the 'Source' field. You can change the color tint or adjust opacity.",
        "ce-docs-water-title": "Water",
        "ce-docs-water-desc": "Physics-based fluid simulation using particles.",
        "ce-docs-water-ins": "Define width and height of the water area. Adjust density (buoyancy) and viscosity.",
        "ce-docs-video-title": "VideoPlayer",
        "ce-docs-video-desc": "Plays video files in the world or UI.",
        "ce-docs-video-ins": "Supports .mp4 and .webm formats. You can enable loop and adjust volume.",
        "ce-docs-physics-title": "3. 2D Physics",
        "ce-docs-rigidbody-title": "Rigidbody2D",
        "ce-docs-rigidbody-desc": "Allows the object to react to gravity and collisions.",
        "ce-docs-rigidbody-ins": "Change body type to 'Dynamic' to fall, or 'Kinematic' to move manually.",
        "ce-docs-colliders-title": "BoxCollider2D / CircleCollider2D",
        "ce-docs-colliders-desc": "Define the physical shape for collisions.",
        "ce-docs-colliders-ins": "Adjust size or radius. If 'Is Trigger' is checked, the object detects overlaps without physical collision.",
        "ce-docs-ai-title": "4. Intelligence and Movement",
        "ce-docs-basicai-title": "BasicAI",
        "ce-docs-basicai-desc": "Automatic behaviors for NPCs and enemies.",
        "ce-docs-patrol-title": "Patrol",
        "ce-docs-patrol-desc": "Moves the object between two points.",
        "ce-docs-ui-title": "5. User Interface (UI)",
        "ce-docs-canvas-title": "Canvas",
        "ce-docs-canvas-desc": "The main container for all UI elements.",
        "ce-docs-button-title": "Button",
        "ce-docs-button-desc": "Detects user clicks.",
        "ce-docs-uitext-title": "UIText",
        "ce-docs-uitext-desc": "Displays text on screen with custom fonts.",
        "ce-docs-anim-title": "6. Animation and Audio",
        "ce-docs-animator-title": "AnimatorController",
        "ce-docs-animator-desc": "Manages animation states (Walk, Jump, Idle).",
        "ce-docs-audio-title": "AudioSource",
        "ce-docs-audio-desc": "Plays sound effects or music. Supports Spatial Audio.",
        "ce-docs-other-title": "7. Other Components",
        "ce-docs-other-list": "RaycastSource, ParticleSystem, Parallax, Light2D.",
        "ce-docs-tip-title": "Scripting Pro-Tip",
        "ce-docs-tip-desc": "Remember that in Creative Engine, you can access any component directly by its name in Spanish. No prefixes needed.",
        "ce-docs-scripting-title": "Scripting Master Guide (CES)",
        "ce-docs-scripting-intro": "Creative Engine uses CES (Creative Engine Script), a powerful language based on JavaScript but simplified for game creators.",
        "ce-docs-scripting-core-title": "Core Concepts",
        "ce-docs-scripting-import": "Every script must start with the engine connection statement: ve motor;",
        "ce-docs-scripting-access": "Direct Access: You DO NOT need to write this. or mtr. to access components.",
        "ce-docs-scripting-vars-title": "Public Variables (Inspector)",
        "ce-docs-scripting-vars-desc": "Define variables so they appear in the Inspector.",
        "ce-docs-scripting-input-title": "Input and Movement",
        "ce-docs-scripting-functions-title": "Special Functions",
        "ce-docs-libs-title": "Library Installation (.celib)",
        "ce-docs-libs-intro": "Libraries extend engine functionality (e.g., Multiplayer, Inventories).",
        "ce-docs-libs-step-1": "Download the .celib file.",
        "ce-docs-libs-step-2": "Move it to the /lib folder of your project.",
        "ce-docs-libs-step-3": "The engine will load it automatically on startup.",
        "ce-docs-carl-title": "Execution with Carl AI",
        "ce-docs-carl-intro": "Carl can automate complex tasks using AI.",
        "ce-docs-carl-modes": "Execution Modes:",
        "ce-docs-carl-mode-1": "Command Mode: Executes immediate actions in the editor.",
        "ce-docs-carl-mode-2": "Scripting Mode: Helps write and debug CES code.",
        "ce-docs-terminal-title": "Terminal Guide",
        "ce-docs-terminal-intro": "The Terminal is an advanced tool for interacting with the engine through text commands.",
        "ce-docs-terminal-activate": "How to Activate the Terminal",
        "ce-docs-terminal-fs-title": "1. File System Commands",
        "ce-docs-terminal-scene-title": "2. Scene Commands",
        "ce-docs-advanced-title": "Advanced Guide: Projects, Scenes, and Build",
        "ce-docs-advanced-intro": "This guide covers the fundamental aspects of asset management, level design, and final game publishing.",
        "ce-docs-advanced-struct-title": "1. Project Structure",
        "ce-docs-advanced-scenes-title": "2. Scene Management (.ceScene)",
        "ce-docs-advanced-build-title": "3. The Build System (Publishing)",
        "ce-docs-editors-title": "Visual Editors Guide",
        "ce-docs-editors-intro": "Creative Engine includes a suite of visual tools to manage graphics, animations, and levels intuitively.",
        "ce-docs-editors-sprite-title": "1. Sprite Editor (Sprite Slicer)",
        "ce-docs-editors-anim-title": "2. Animation Editor (.cea)",
        "ce-docs-editors-tilemap-title": "3. Tilemap Editor",
        "ce-docs-config-title": "Configuration and Atmosphere Guide",
        "ce-docs-config-intro": "Learn how to customize your workflow and configure the technical parameters of your project.",
        "ce-docs-config-project-title": "1. Project Configuration",
        "ce-docs-config-ambient-title": "2. Atmosphere Control",
        "ce-docs-carl-keys": "Configure your key in Edit > Preferences > AI. We support Google Gemini (Free), OpenAI, and Anthropic.",
        "ce-docs-carl-skill-1": "\"Create an object named Player with SpriteRenderer.\"",
        "ce-docs-carl-skill-2": "\"Create a script that moves the player with arrows.\"",
        "ce-docs-terminal-ls": "ls: List files.",
        "ce-docs-terminal-cd": "cd <folder>: Change folder.",
        "ce-docs-terminal-clear": "clear: Clear terminal.",
        "ce-docs-terminal-act-1": "Window > Terminal",
        "ce-docs-terminal-act-2": "Bottom Panel > Terminal Tab.",
        "ce-docs-advanced-struct-1": "/Assets: Images, sounds, scripts.",
        "ce-docs-advanced-struct-2": "/lib: Libraries (.celib).",
        "ce-docs-advanced-struct-3": "project.ceconfig: Technical configuration.",
        "ce-docs-advanced-scenes-desc": "Use Ctrl + S to save. Scenes (.ceScene) contain all objects and lights.",
        "ce-docs-advanced-build-desc": "Generates a standalone web package (.zip) ready for hosting.",
        "ce-docs-editors-sprite-desc": "Slice large images into multiple small sprites.",
        "ce-docs-editors-anim-desc": "Create sequences (.cea) using a timeline.",
        "ce-docs-editors-tilemap-desc": "Design grid-based levels with brushes and layers.",
        "ce-docs-config-project-desc": "Manage Sorting Layers, Collision Layers, and Tags.",
        "ce-docs-config-ambient-desc": "Day/Night cycle, color filters, and ambient lights.",
        "ce-docs-transform-name": "Transform",
        "ce-docs-transform-inspector": "Inspector Use: Edit X and Y values to move the object. Use flip buttons to invert the image.",
        "ce-docs-camera-name": "Camera",
        "ce-docs-camera-inspector": "Inspector Use: Configure background color, zoom, and culling mask to decide which objects this camera sees.",
        "ce-docs-sprite-name": "SpriteRenderer",
        "ce-docs-sprite-inspector": "Inspector Use: Drag an image to the \"Source\" field. You can change the color to tint the image or adjust opacity.",
        "ce-docs-water-name": "Water",
        "ce-docs-water-inspector": "Inspector Use: Define width and height of the water area. Adjust density (buoyancy) and viscosity.",
        "ce-docs-video-name": "VideoPlayer",
        "ce-docs-video-inspector": "Inspector Use: Supports .mp4 and .webm formats. You can enable loop and adjust volume.",
        "ce-docs-rigidbody-name": "Rigidbody2D",
        "ce-docs-rigidbody-inspector": "Inspector Use: Change body type to \"Dynamic\" to fall, or \"Kinematic\" to move manually but detect collisions.",
        "ce-docs-collider-name": "BoxCollider2D / CircleCollider2D",
        "ce-docs-collider-desc": "Define the physical shape for collisions.",
        "ce-docs-collider-inspector": "Inspector Use: Adjust size or radius. If you check \"Is Trigger\", the object won't collide but will detect when something enters its area.",
        "ce-docs-basicai-name": "BasicAI",
        "ce-docs-basicai-modes": "Modes: Follow (Follows a Matter), Escape (Flees from a target), Wander (Walks randomly).",
        "ce-docs-patrol-name": "Patrol",
        "ce-docs-canvas-name": "Canvas",
        "ce-docs-button-name": "Button",
        "ce-docs-button-inspector": "Inspector Use: Allows defining colors for states (Normal, Pressed, Disabled) or changing sprites.",
        "ce-docs-uitext-name": "UIText",
        "ce-docs-animator-name": "AnimatorController",
        "ce-docs-animator-inspector": "Inspector Use: Requires a .ceanim file. \"Smart Mode\" animates automatically based on movement.",
        "ce-docs-audio-name": "AudioSource",
        "ce-docs-audio-inspector": "Inspector Use: Supports Spatial Audio (volume drops as object moves away).",
        "ce-docs-others-title": "7. Other Components",
        "ce-docs-others-raycast": "RaycastSource (Ray): Casts invisible rays to detect walls or enemies.",
        "ce-docs-others-particles": "ParticleSystem (Particles): Creates fire, smoke, or spark effects.",
        "ce-docs-others-parallax": "Parallax: Creates infinite backgrounds with depth.",
        "ce-docs-others-light": "Light2D (Lights): Illuminates your scene with point or spot lights.",
        "ce-docs-protip-title": "Scripting Pro-Tip",
        "ce-docs-protip-desc": "Remember that in Creative Engine, you can access any component directly by its name. No prefixes needed.",
        "ce-docs-scripting": "Scripting",
        // Scripting Guide
        "ce-docs-scripting-events-title": "Lifecycle Events",
        "ce-docs-scripting-example-title": "Practical Examples",
        // Libraries Guide
        "ce-docs-libs-ui-title": "1. Interface Libraries (Editor Tools)",
        "ce-docs-libs-runtime-title": "2. Runtime Libraries (New Functions)",
        "ce-docs-libs-install-title": "How to Create and Install a Library",
        // Carl IA Guide
        "ce-docs-carl-activate-title": "How to Activate Carl IA",
        "ce-docs-carl-config-title": "Configuration (API Keys)",
        "ce-docs-carl-skills-title": "Autonomous Skills",
        "ce-docs-carl-modes-title": "Execution Modes",
        "ce-solutions-title": "Quick Solutions",
        "ce-solutions-placeholder": "For now, there are no quick solutions, but if you find any bugs, please report them. This way we will start adding ways to solve them.",
        "ce-nav-tutorials": "Tutorials",
        "ce-tutorial-ui-title": "Learn the Creative Engine interface",
        "ce-tutorial-ui-desc": "Learn the Creative Engine interface to create with ease. You will discover everything the engine has at launch and what each tool is for; this way you will better know how to create your video game.",
        "ce-tutorial-carl-title": "How to activate Carl",
        "ce-tutorial-carl-desc": "Learn how to activate Carl, your development companion who will accompany you in the development of your video games.",
        "ce-tutorial-prog-title": "How to program in Creative Engine",
        "ce-tutorial-prog-desc": "Learn to program your own video games using CES (Creative Engine Scripting) and other coding tools.",
        "ce-tutorial-title": "How to create your first game",
        "ce-tutorial-desc": "Learn the fundamentals of Creative Engine and start your adventure as a developer.",
        "tutorial-not-available": "This tutorial is not yet available, do you want to see our channel and other videos?",
        "ce-donate-intro": "Your support is what keeps this project alive and free for everyone. With total transparency, we share that maintaining Creative Engine requires covering server and development costs so that it remains an accessible tool for everyone without economic barriers. Your donations will help others use our tools for free.",
        "ce-info-1": "Creative Engine was designed for everyone. It doesn't matter if you're an expert, a novice, or have no experience at all, Creative Engine helps and teaches you.",
        "ce-info-2": "Our engine was inspired by Unity but is based on matters and laws. Matters can be anything in your game and laws are everything that defines the behavior of each thing in your game; they are a set of rules that make your game unique and make it what you want it to be.",
        "ce-why-title": "Why use Creative Engine?",
        "ce-why-1": "The engine is in several different languages and has 3 ways of coding:",
        "ce-ces-desc": "Designed for those who are already experts in video game creation and like to program with pure code. Made with JS and inspired by C#, JS, and Python. Allows programming entirely in Spanish, English, Portuguese, Russian, and Chinese (and will be extended to more languages).",
        "ce-scratch-desc": "You can create game logic by dragging blocks. Great for those who are just starting out. Still in development.",
        "ce-human-desc": "Here you just have to talk to the engine, tell it what you want the script to do, and the engine will understand you.",
        "ce-info-3": "You can create a game in less than 1 hour and without writing a single line of code. The engine includes several basic components that help you create your games. Being web-based, you can publish them on multiple platforms and for various devices.",
        "ce-info-4": "Our engine has a library system that allows developers to create various libraries. If you want, for example, an AI for your game, you don't have to make an advanced AI from scratch; just download the library and that's it.",
        "ce-info-5": "Our engine has Carl IA integrated, which will help you make your ideas a reality and guide you through every step of your development.",
        "ce-info-free": "Creative Engine is 100% free. We do not claim rights to any game made with it; in fact, the more you create, the happier we are.",
        "ce-info-open": "The engine itself will be available in open source for all those who want to modify it to their liking.",
        "ce-info-team": "Creative Engine is developing a system that will allow you to create video games as a team. Great for schools that want to teach video game development to students or small studios.",
        "ce-info-vidspri": "Creative Engine has Vid Spri integrated, a tool that allows you to create animations and sound for your video games.",
        "ph-bug-desc": "Describe the bug...",
        "field-message": "Message",
        "field-photos": "Photos (Max 5)",
        "btn-send": "Send Report",
        "field-opinion": "Your Opinion",
        "ph-opinion": "What do you think of Creative Engine?",
        "btn-send-opinion": "Publish Opinion",
        "opinion-hint": "We will read your opinions and consider all those with more likes in future updates.",
        "ce-license-1": "Games made are available under the CLG1 license (Carley Free).",
        "ce-license-2": "The licensee has every right to use it however they want in their entire product. We do not claim any percentage.",
        "ce-license-3": "We are not responsible; that is, we do not have an obligation to resolve bugs, failures, or errors that the product may present.",
        "ce-license-4": "We have no rights in the user's product unless they allow us.",
        "ce-license-date": "Last updated: March 4, 2026",
        "ce-privacy-main": "We do not store any other type of data other than information necessary for your account and opinions on our servers, etc.",
        "ce-claim-reason": "Reason for the claim",
        "claim-hint": "You can claim in the same week that you have made the donations; thereafter we do not guarantee a refund.",
        "btn-send-claim": "Send Claim",
        "ce-donate-1": "You don't need to be a developer to contribute to our engine. Your monetary support will help us hire developers and pay for servers to make Vid Spri a very useful and free tool.",
        "ce-donate-2": "It will fund us to keep moving forward and pay for servers so that in the future you can use Carl IA without depending on an external API for free.",
        "btn-support": "Support",
        "btn-ad": "Watch an ad to support us",
        "ce-donate-claim": "If in any case you want to make a claim you can do it from Claims.",
        "ce-nav-credits": "Credits",
        "credits-main": "This project wouldn't be possible without the incredible help of Google Jules, who has done much of the project. We thank Google for their generous free plans.",
        "credits-ms": "We also thank Microsoft Copilot, which has also significantly contributed to the project.",
        "credits-gemini": "Finally, we thank Google AI Studio for their generous plan and their Gemini model for the free use of Carl IA.",
        // Vid Spri
        "vs-nav-tutorials": "Tutorials",
        "vs-donate-intro": "Your support is what allows Vid Spri to remain a free and open access tool. We want every creator to have the best tools regardless of their budget, and therefore we maintain total transparency about the server costs necessary for the AI to work for you. Your donations will help others use our tools for free.",
        "vs-info-1": "VidSpri was created with novice developers in mind or those who want to create their 2D video games but have no experience drawing each frame.",
        "vs-info-2": "Many have turned to AI to generate frames for their characters, but AI can't do this job well either; it doesn't know how to do it until we realized that AI, when generating video, does it much better than when it generates a simple image with several sprites.",
        "vs-info-3": "We came up with the idea of making a tool that converts videos to sprite sheets. Our tool takes frames from videos and converts them into a sprite sheet or generates a video to take frames from it, achieving a better result.",
        "vs-info-4": "To make it more complete, we've made it possible to generate sound for your video games.",
        "vs-credits-main": "VidSpri Development and Assistance Credits is a project of Carley Interactive Studio. This project was developed with the assistance of Jules, a Google AI software engineer. We thank Google for providing access to this incredible tool that made it possible to accelerate and improve our development process.",
        "vs-credits-hf": "Special Thanks We want to extend a special thanks to Hugging Face for providing free hosting for our servers through their Spaces platform. Their support for the open-source community is what allows tools like VidSpri to be available to everyone for free.",
        "vs-credits-os": "Open Source Technologies and Libraries This application would not be possible without the incredible work of the open-source community. We thank the developers and maintainers of the following technologies and libraries:",
        "donate-big-title": "Your support is worth a lot",
        "donate-intro-msg": "You are contributing so that others can use our app and engine for free.",
        "transparency-title": "Our Mission",
        "transparency-desc-long": "We want VidSpri to be free for everyone, without freemium or premium models. We want everyone to have the same access to all tools to create animations and music. Creative Engine is already free, and we want Carl IA to be too, fully integrated. To maintain this, we need to cover server costs for Hugging Face and Supabase.",
        "support-action-title": "Support project",
        "vs-tutorial-title": "Tutorials",
        "vs-tutorial-desc": "Learn how to use Vid Spri for your projects.",
        "vs-donate-1": "You don't need to be a developer to contribute to our project. Your monetary support will help us hire developers and pay for servers to make Vid Spri a very useful and free tool.",
        "vs-os-python-desc": "The programming language that powers our entire backend.",
        "vs-os-docker-desc": "The container platform that allows us to deploy the server reliably.",
        "vs-os-fastapi-desc": "A modern, fast web framework for building our APIs.",
        "vs-os-uvicorn-desc": "An ultra-fast ASGI server, used to run the backend application.",
        "vs-os-rembg-desc": "The powerful library used to intelligently remove background from images.",
        "vs-os-pillow-desc": "A fundamental library for image manipulation in Python.",
        "vs-os-onnx-desc": "The high-performance inference engine that powers the rembg model.",
        "vs-os-multipart-desc": "Essential library for file upload management on the server.",
        "vs-os-sqlite-desc": "The database engine used to manage the processing queue and priority codes.",
        "vs-os-translate-desc": "The service that powers the translation functionality in the application.",
        "vs-os-feather-desc": "The open-source icon library that provides the user interface icons.",
        "vs-os-crop-desc": "A JavaScript library for image cropping functionality on the frontend.",
        "support-title": "Support for everyone",
        "support-intro": "Absolute transparency. Here you can see how Carley apps stay free for the world.",
        "stat-total-users": "Total Users",
        "stat-monthly-goal": "Monthly Goal",
        "stat-collected-label": "Collected",
        "list-title": "Our Contributors",
        "col-name": "Name",
        "col-amount": "Contribution",
        "empty-supporters": "No contributions recorded this month yet. Be the first!",
        "support-how-to": "Want to appear here? Support us via PayPal in the donations section of our apps.",
        "btn-go-donate": "Go to Donate"
    },
    },
    fr: {
    fr: {
        welcome: "Bienvenue, nous sommes ravis de vous voir ici",
        "btn-yes": "Oui",
        "btn-no": "Non",
        "search-ph": "Rechercher dans Carley...",
        "hero-desc": "Avez-vous déjà pensé à développer votre propre jeu vidéo ? Eh bien, nous avons conçu Creative Engine pour vous, un moteur de jeu vidéo 2D qui facilite tout. Que vous ayez de l'expérience dans la création de jeux ou non, Creative Engine est fait pour vous. Quelle que soit votre idée, Creative Engine vous aide à la concrétiser.",
        "hero-cta": "Commencer à créer",
        "carl-ia-desc": "Notre IA actuellement en développement. Très bientôt, elle sera disponible pour vous aider dans tout ce dont vous avez besoin. Notre modèle sera complet : il aura une vision, pourra parler, générer du texte et écouter. Nous l'entraînons pour être le compagnon intégral ultime.",
        "learn-more": "En savoir plus",
        "traspilador-desc": "Conçu pour les développeurs. Un modèle de codage capable de convertir des projets d'un langage à un autre (exemple : de JS à C++). Simplifiez la migration de vos projets et accélérez votre flux de travail.",
        "explore-docs": "Explorer la documentation",
        "footer-channels": "Chaînes",
        "footer-donations": "Dons",
        "footer-info": "Information",
        "footer-products": "Nos produits",
        "footer-donate-paypal": "Faire un don avec PayPal",
        "footer-donate-info": "Que faisons-nous de vos dons ?",
        "footer-privacy": "Politique de confidentialité",
        "footer-license": "Licence",
        "footer-copyright": "© 2026 Carley Interactive Studio. Tous droits réservés.",
        "acc-modal-title": "Mon compte",
        "field-email": "E-mail",
        "field-username": "Nom d'utilisateur",
        "btn-update": "Mettre à jour le profil",
        "btn-logout": "Se déconnecter",
        "modal-hint": "Connectez-vous pour gérer vos projets.",
        "btn-login": "Entrer",
        "btn-register": "Créer un compte",
        "login-title": "Se connecter",
        "ph-email": "E-mail",
        "ph-pass": "Mot de passe",
        "ph-pass-confirm": "Confirmer le mot de passe",
        "btn-login-action": "Entrer",
        "register-title": "Créer un compte",
        "btn-register-action": "S'inscrire",
        "donations-modal-title": "Que faisons-nous de vos dons ?",
        "donations-modal-desc": "Votre soutien nous permet d'embaucher plus de talents, d'améliorer nos serveurs et d'accélérer le développement d'outils gratuits pour la communauté comme Creative Engine. Chaque don est investi directement dans l'amélioration de nos technologies.",
        "privacy-modal-title": "Confidentialité",
        "privacy-modal-desc": "Vos données sont en sécurité. Nous les utilisons uniquement pour améliorer votre expérience sur notre plateforme.",
        "license-modal-title": "Licence",
        "license-modal-desc": "Tous nos produits sont protégés par les lois internationales sur la propriété intellectuelle.",
        "ce-nav-tutorials": "Tutoriels",
        "ce-nav-solutions": "Solutions Rapides",
        "ce-nav-docs": "Documentation",
        "ce-docs-terminal-title": "Guide du Terminal",
        "ce-docs-terminal-intro": "Le Terminal est un outil avancé pour interagir avec le moteur via des commandes textuelles.",
        "ce-docs-terminal-activate": "Comment Activer le Terminal",
        "ce-docs-terminal-fs-title": "1. Commandes du Système de Fichiers",
        "ce-docs-terminal-scene-title": "2. Commandes de Scène",
        "ce-docs-advanced-title": "Guide Avancé : Projets, Scènes et Build",
        "ce-docs-advanced-intro": "Ce guide couvre les aspects fondamentaux de la gestion des ressources, de la conception des niveaux et de la publication finale du jeu.",
        "ce-docs-advanced-struct-title": "1. Structure du Projet",
        "ce-docs-advanced-scenes-title": "2. Gestion des Scènes (.ceScene)",
        "ce-docs-advanced-build-title": "3. Le Système de Build (Publication)",
        "ce-docs-editors-title": "Guide des Éditeurs Visuels",
        "ce-docs-editors-intro": "Creative Engine comprend une suite d'outils visuels pour gérer les graphismes, les animations et les niveaux de manière intuitive.",
        "ce-docs-editors-sprite-title": "1. Éditeur de Sprites (Sprite Slicer)",
        "ce-docs-editors-anim-title": "2. Éditeur d'Animations (.cea)",
        "ce-docs-editors-tilemap-title": "3. Éditeur de Tilemap",
        "ce-docs-config-title": "Guide de Configuration et d'Atmosphère",
        "ce-docs-config-intro": "Apprenez à personnaliser votre flux de travail et à configurer les paramètres techniques de votre projet.",
        "ce-docs-config-project-title": "1. Configuration du Projet",
        "ce-docs-config-ambient-title": "2. Contrôle de l'Atmosphère",
        "ce-docs-carl-keys": "Configurez votre clé dans Éditer > Préférences > IA. Nous supportons Google Gemini (Gratuit), OpenAI et Anthropic.",
        "ce-docs-carl-skill-1": "\"Crée un objet appelé Joueur avec SpriteRenderer.\"",
        "ce-docs-carl-skill-2": "\"Crée un script qui déplace le joueur avec les flèches.\"",
        "ce-docs-terminal-ls": "ls : Lister les fichiers.",
        "ce-docs-terminal-cd": "cd <dossier> : Changer de dossier.",
        "ce-docs-terminal-clear": "clear : Effacer le terminal.",
        "ce-docs-terminal-act-1": "Fenêtre > Terminal",
        "ce-docs-terminal-act-2": "Panneau Inférieur > Onglet Terminal.",
        "ce-docs-advanced-struct-1": "/Assets : Images, sons, scripts.",
        "ce-docs-advanced-struct-2": "/lib : Bibliothèques (.celib).",
        "ce-docs-advanced-struct-3": "project.ceconfig : Configuration technique.",
        "ce-docs-advanced-scenes-desc": "Utilisez Ctrl + S pour sauvegarder. Les scènes (.ceScene) contiennent tous les objets et lumières.",
        "ce-docs-advanced-build-desc": "Génère un paquet web indépendant (.zip) prêt pour l'hébergement.",
        "ce-docs-editors-sprite-desc": "Découpez de grandes images en plusieurs petits sprites.",
        "ce-docs-editors-anim-desc": "Créez des séquences (.cea) en utilisant une ligne de temps.",
        "ce-docs-editors-tilemap-desc": "Concevez des niveaux basés sur une grille avec des pinceaux et des calques.",
        "ce-docs-config-project-desc": "Gérez les Sorting Layers, Collision Layers et Tags.",
        "ce-docs-config-ambient-desc": "Cycle Jour/Nuit, filtres de color et lumières d'ambiance.",
        "ce-docs-scripting-title": "Guide Maître du Scripting (CES)",
        "ce-docs-scripting-intro": "Creative Engine utilise CES (Creative Engine Script), un langage puissant basé sur JavaScript mais simplifié pour les créateurs de jeux.",
        "ce-docs-scripting-core-title": "Concepts Fondamentaux",
        "ce-docs-scripting-import": "Tout script doit commencer par l'instruction de connexion au moteur : ve motor;",
        "ce-docs-scripting-access": "Accès Direct : Vous N'AVEZ PAS besoin d'écrire this. ou mtr. pour accéder aux composants.",
        "ce-docs-scripting-vars-title": "Variables Publiques (Inspecteur)",
        "ce-docs-scripting-vars-desc": "Pour qu'une variable apparaisse dans l'Inspecteur, utilisez le mot-clé publico.",
        "ce-docs-scripting-events-title": "Événements de Cycle de Vie",
        "ce-docs-scripting-input-title": "Entrée (Input) et Mouvement",
        "ce-docs-scripting-example-title": "Exemples Pratiques",
        "ce-docs-scripting-functions-title": "Fonctions Spéciales",
        "ce-docs-libs-title": "Guide des Bibliothèques et de l'Extensibilité",
        "ce-docs-libs-intro": "Les bibliothèques (.celib) permettent d'étendre à la fois l'interface de l'éditeur et les capacités de programmation.",
        "ce-docs-libs-ui-title": "1. Bibliothèques d'Interface (Outils de l'Éditeur)",
        "ce-docs-libs-runtime-title": "2. Bibliothèques de Runtime (Nouvelles Fonctions)",
        "ce-docs-libs-install-title": "Comment Créer et Installer une Bibliothèque",
        "ce-docs-carl-title": "Guide de Carl IA : Votre Assistant Autonome",
        "ce-docs-carl-intro": "Carl IA est un agent intelligent capable de manipuler l'éditeur, de créer des fichiers et de vous aider à construire votre jeu étape par étape.",
        "ce-docs-carl-activate-title": "Comment Activer Carl IA",
        "ce-docs-carl-config-title": "Configuration (Clés API)",
        "ce-docs-carl-skills-title": "Compétences Autonomes",
        "ce-docs-carl-modes-title": "Modes d'Exécution",
        "ce-docs-carl-modes-desc": "Carl peut travailler en mode \"Assistant\" (vous guide) ou \"Autonome\" (effectue les changements pour vous).",
        "ce-docs-carl-act-1": "Bouton Supérieur : Icône du robot (Carl)",
        "ce-docs-carl-act-2": "Raccourci : Shift + Ctrl + L",
        "ce-solutions-title": "Solutions Rapides",
        "ce-solutions-placeholder": "Pour l'instant, il n'y a pas de solutions rapides, mais si vous trouvez des bugs, veuillez les signaler. De cette façon, nous commencerons à ajouter des moyens de les résoudre.",
        "ce-tutorial-ui-title": "Apprenez l'interface de Creative Engine",
        "ce-tutorial-ui-desc": "Apprenez l'interface de Creative Engine pour créer avec facilité. Vous découvrirez tout ce que le moteur propose à son lancement et à quoi sert chaque outil ; ainsi, vous saurez mieux comment créer votre jeu vidéo.",
        "ce-tutorial-carl-title": "Comment activer Carl",
        "ce-tutorial-carl-desc": "Apprenez à activer Carl, votre compagnon de développement qui vous accompagnera dans le développement de vos jeux vidéo.",
        "ce-tutorial-prog-title": "Comment programmer dans Creative Engine",
        "ce-tutorial-prog-desc": "Apprenez à programmer vos propres jeux vidéo en utilisant CES (Creative Engine Scripting) et d'autres outils de codage.",
        "tutorial-not-available": "Ce tutoriel n'est pas encore disponible, voulez-vous voir notre chaîne et d'autres vidéos ?",
        // Vid Spri (FR)
        "vs-nav-tutorials": "Tutoriels",
        "ce-docs-leyes-title": "Guide des Composants (Lois) - Creative Engine",
        "ce-docs-leyes-intro": "Dans Creative Engine, les Matières (objets) prennent vie à travers les Lois (composants). Chaque Loi ajoute une fonctionnalité spécifique, telle que la gravité, le rendu d'image ou la logique d'IA. Ce guide détaille l'utilisation des composants tant dans l'Inspecteur que dans les Scripts (.ces) en utilisant la syntaxe moderne (sans préfixes comme this. ou motor.).",
        "ce-docs-core-title": "1. Composants de Base (Core)",
        "ce-docs-transform-name": "Transform (Transformation)",
        "ce-docs-transform-desc": "Définit la position, la rotation et l'échelle d'un objet dans l'espace 2D.",
        "ce-docs-transform-inspector": "Utilisation dans l'Inspecteur : Modifiez les valeurs X et Y pour déplacer l'objet. Utilisez les boutons de retournement (Flip) pour inverser l'image.",
        "ce-docs-camera-name": "Camera (Caméra)",
        "ce-docs-camera-desc": "Définit la zone visible du jeu.",
        "ce-docs-camera-inspector": "Utilisation dans l'Inspecteur : Configurez la couleur d'arrière-plan, le zoom et le masque de calque (Culling Mask) pour décider quels objets cette caméra voit.",
        "ce-docs-render-title": "2. Rendu et Visuels",
        "ce-docs-sprite-name": "SpriteRenderer (Rendu de Sprite)",
        "ce-docs-sprite-desc": "Affiche une image (.png, .jpg) ou une image d'une feuille de sprites (.ceSprite).",
        "ce-docs-sprite-inspector": "Utilisation dans l'Inspecteur : Faites glisser une image vers le champ \"Source\". Vous pouvez changer la couleur pour teinter l'image ou ajuster l'opacité.",
        "ce-docs-water-name": "Water (Eau)",
        "ce-docs-water-desc": "Simulation physique des fluides basée sur des particules.",
        "ce-docs-water-inspector": "Utilisation dans l'Inspecteur : Définit la largeur et la hauteur de la zone d'eau. Ajustez la densité (flottabilité) et la viscosité.",
        "ce-docs-video-name": "VideoPlayer (Lecteur Vidéo)",
        "ce-docs-video-desc": "Lit des fichiers vidéo dans le monde ou dans l'interface utilisateur.",
        "ce-docs-video-inspector": "Utilisation dans l'Inspecteur : Prend en charge les formats .mp4 et .webm. Vous pouvez activer la boucle (loop) et régler le volume.",
        "ce-docs-physics-title": "3. Physique 2D",
        "ce-docs-rigidbody-name": "Rigidbody2D (Physique)",
        "ce-docs-rigidbody-desc": "Permet à l'objet de réagir à la gravité et aux collisions.",
        "ce-docs-rigidbody-inspector": "Utilisation dans l'Inspecteur : Changez le type de corps en \"Dynamic\" pour qu'il tombe, ou en \"Kinematic\" pour le déplacer manuellement tout en détectant les collisions.",
        "ce-docs-collider-name": "BoxCollider2D / CircleCollider2D (Collisionneurs)",
        "ce-docs-collider-desc": "Définissent la forme physique pour les chocs.",
        "ce-docs-collider-inspector": "Utilisation dans l'Inspecteur : Ajustez la taille ou le rayon. Si vous cochez \"Is Trigger\", l'objet n'entrera pas en collision mais détectera quand quelque chose pénètre dans sa zone.",
        "ce-docs-ai-title": "4. Intelligence et Mouvement",
        "ce-docs-basicai-name": "BasicAI (IA de Base)",
        "ce-docs-basicai-desc": "Comportements automatiques pour les PNJ et les ennemis.",
        "ce-docs-basicai-modes": "Modes : Follow (Suit une Matière), Escape (Fuit une cible), Wander (Marche aléatoirement).",
        "ce-docs-patrol-name": "Patrol (Patrouille)",
        "ce-docs-patrol-desc": "Déplace l'objet entre deux points.",
        "ce-docs-ui-title": "5. Interface Utilisateur (UI)",
        "ce-docs-canvas-name": "Canvas (Canevas)",
        "ce-docs-canvas-desc": "Le conteneur principal pour tous les éléments d'interface.",
        "ce-docs-button-name": "Button (Bouton)",
        "ce-docs-button-desc": "Détecte les clics de l'utilisateur.",
        "ce-docs-button-inspector": "Utilisation dans l'Inspecteur : Permet de définir des couleurs pour les états (Normal, Pressé, Désactivé) ou de changer les sprites.",
        "ce-docs-uitext-name": "UIText (Texte UI)",
        "ce-docs-uitext-desc": "Affiche du texte à l'écran avec des polices personnalisées.",
        "ce-docs-anim-title": "6. Animation et Audio",
        "ce-docs-animator-name": "AnimatorController (Contrôleur)",
        "ce-docs-animator-desc": "Gère les états d'animation (Marcher, Sauter, Inactif).",
        "ce-docs-animator-inspector": "Utilisation dans l'Inspecteur : Nécessite un fichier .ceanim. Le \"Smart Mode\" anime automatiquement selon le mouvement.",
        "ce-docs-audio-name": "AudioSource (Source Audio)",
        "ce-docs-audio-desc": "Joue des effets sonores ou de la musique.",
        "ce-docs-audio-inspector": "Utilisation dans l'Inspecteur : Prend en charge l'audio spatial (le volume baisse si l'objet s'éloigne).",
        "ce-docs-others-title": "7. Autres Composants",
        "ce-docs-others-raycast": "RaycastSource (Rayon) : Lance des rayons invisibles pour détecter les murs ou les ennemis.",
        "ce-docs-others-particles": "ParticleSystem (Particules) : Crée des effets de feu, de fumée ou d'étincelles.",
        "ce-docs-others-parallax": "Parallax : Crée des arrière-plans infinis avec de la profondeur.",
        "ce-docs-others-light": "Light2D (Lumières) : Illumine votre scène avec des lumières ponctuelles ou focales.",
        "ce-docs-protip-title": "Pro-Tip de Scripting",
        "ce-docs-protip-desc": "N'oubliez pas que dans Creative Engine, vous pouvez accéder à n'importe quel composant directement par son nom. Aucun préfixe n'est nécessaire.",
        "ce-docs-scripting": "Scripting",
        "vs-info-1": "VidSpri a été créé pour les développeurs débutants ou ceux qui souhaitent créer leurs jeux vidéo 2D mais n'ont aucune expérience dans le dessin de chaque image.",
        "vs-info-2": "Beaucoup se sont tournés vers l'IA pour générer des images pour leurs personnages, mais l'IA ne peut pas non plus bien faire ce travail ; elle ne sait pas comment s'y prendre jusqu'à ce que nous réalisions que l'IA, lorsqu'elle génère de la vidéo, le fait bien mieux que lorsqu'elle génère une simple image avec plusieurs sprites.",
        "vs-info-3": "Nous avons eu l'idée de créer un outil qui convertit des vidéos en feuilles de sprites. Notre outil extrait des images de vidéos et les convertit en une feuille de sprites ou génère une vidéo pour en extraire des images, obtenant ainsi un meilleur résultat.",
        "vs-info-4": "Pour le rendre plus complet, nous avons permis de générer du son pour vos jeux vidéo.",
        "vs-credits-main": "Crédits de Développement et d'Assistance VidSpri est un projet de Carley Interactive Studio. Ce projet a été développé avec l'assistance de Jules, un ingénieur logiciel IA de Google.",
        "vs-credits-hf": "Remerciements spéciaux à Hugging Face pour l'hébergement gratuit de nos serveurs via Spaces.",
        "vs-credits-os": "Technologies et Bibliothèques Open Source",
        "vs-tutorial-title": "Tutoriels",
        "vs-tutorial-desc": "Apprenez à utiliser Vid Spri pour vos projets.",
        "vs-donate-1": "Votre soutien monétaire nous aidera à embaucher des développeurs et à payer des serveurs pour faire de Vid Spri un outil gratuit.",
        "vs-os-python-desc": "Le langage de programmation qui propulse tout notre backend.",
        "vs-os-docker-desc": "La plateforme de conteneurs pour déployer le serveur de manière fiable.",
        "vs-os-fastapi-desc": "Un framework web moderne et rapide pour construire nos API.",
        "vs-os-uvicorn-desc": "Un serveur ASGI ultra-rapide utilisé pour exécuter l'application backend.",
        "vs-os-rembg-desc": "Bibliothèque puissante pour supprimer intelligemment l'arrière-plan des images.",
        "vs-os-pillow-desc": "Bibliothèque fondamentale pour la manipulation d'images en Python.",
        "vs-os-onnx-desc": "Moteur d'inférence haute performance pour le modèle rembg.",
        "vs-os-multipart-desc": "Essentiel pour la gestion des téléchargements de fichiers sur le serveur.",
        "vs-os-sqlite-desc": "Moteur de base de données pour gérer la file d'attente et les codes de priorité.",
        "vs-os-translate-desc": "Service qui alimente la fonctionnalité de traduction.",
        "vs-os-feather-desc": "Bibliothèque d'icônes open source pour l'interface utilisateur.",
        "vs-os-crop-desc": "Bibliothèque JavaScript pour le recadrage d'images sur le frontend.",
        "ce-nav-docs-leyes": "Composants",
        "ce-nav-docs-scripting": "Scripting",
        "ce-nav-docs-libs": "Bibliothèques",
        "ce-nav-docs-carl": "Carl AI",
        "ce-nav-docs-terminal": "Terminal",
        "ce-nav-docs-editors": "Éditeurs",
        "ce-nav-docs-advanced": "Avancé",
        "ce-nav-docs-config": "Configuration",
        "ce-docs-leyes-inspector": "Utilisation dans l'Inspecteur :",
        "ce-docs-leyes-scripting": "Scripting :",
        "ce-docs-transform-title": "Transform (Transformation)",
        "ce-docs-transform-ins": "Modifiez les valeurs X et Y pour déplacer l'objet. Utilisez les boutons Flip pour inverser l'image.",
        "ce-docs-camera-title": "Camera (Caméra)",
        "ce-docs-camera-ins": "Configurez la couleur d'arrière-plan, le zoom et le masque de calque (Culling Mask).",
        "ce-docs-sprite-title": "SpriteRenderer (Rendu de Sprite)",
        "ce-docs-sprite-ins": "Faites glisser une image dans le champ 'Source'. Vous pouvez changer la couleur ou ajuster l'opacité.",
        "ce-docs-water-title": "Water (Eau)",
        "ce-docs-water-ins": "Définit la largeur et la hauteur de la zone d'eau. Ajustez la densité (flottaison) et la viscosité.",
        "ce-docs-video-title": "VideoPlayer (Lecteur Vidéo)",
        "ce-docs-video-ins": "Prend en charge les formats .mp4 et .webm. Vous pouvez activer la boucle et régler le volume.",
        "ce-docs-rigidbody-title": "Rigidbody2D (Physique)",
        "ce-docs-rigidbody-ins": "Changez le type de corps en 'Dynamic' pour qu'il tombe, ou 'Kinematic' pour le déplacer manuellement.",
        "ce-docs-colliders-title": "BoxCollider2D / CircleCollider2D",
        "ce-docs-colliders-desc": "Définissent la forme physique pour les chocs.",
        "ce-docs-colliders-ins": "Ajustez la taille ou le rayon. 'Is Trigger' permet de détecter sans collision physique.",
        "ce-docs-basicai-title": "BasicAI (IA de Base)",
        "ce-docs-patrol-title": "Patrol (Patrouille)",
        "ce-docs-canvas-title": "Canvas (Canevas)",
        "ce-docs-button-title": "Button (Bouton)",
        "ce-docs-uitext-title": "UIText (Texte UI)",
        "ce-docs-animator-title": "AnimatorController (Contrôleur)",
        "ce-docs-audio-title": "AudioSource (Source Audio)",
        "ce-docs-other-title": "7. Autres Composants",
        "ce-docs-other-list": "RaycastSource (Rayon), ParticleSystem (Particules), Parallax (Parallaxe), Light2D (Lumières).",
        "ce-docs-tip-title": "Conseil de Scripting",
        "ce-docs-tip-desc": "N'oubliez pas que dans Creative Engine, vous pouvez accéder à n'importe quel composant directement par son nom. Vous n'avez pas besoin d'utiliser de préfixes.",
        "ce-docs-libs-step-1": "Téléchargez le fichier .celib.",
        "ce-docs-libs-step-2": "Déplacez-le dans le dossier /lib de votre projet.",
        "ce-docs-libs-step-3": "Le moteur le chargera automatiquement au démarrage.",
        "ce-docs-carl-modes": "Modes d'Exécution :",
        "ce-docs-carl-mode-1": "Mode Commande : Exécute des actions immédiates dans l'éditeur.",
        "ce-docs-carl-mode-2": "Mode Scripting : Aide à écrire et déboguer du code CES.",
    },
    },
    pt: {
    pt: {
        welcome: "Bem-vindo, estamos felizes em tê-lo aqui",
        "btn-yes": "Sim",
        "btn-no": "Não",
        "search-ph": "Pesquisar em Carley...",
        "hero-desc": "Já pensou em desenvolver seu próprio videogame? Bem, projetamos o Creative Engine para você, um motor de videogame 2D que facilita tudo. Não importa se você tem experiência na criação de jogos ou não, o Creative Engine foi feito para você. Qualquer ideia que você tenha, o Creative Engine ajuda a torná-la realidade.",
        "hero-cta": "Começar a criar",
        "carl-ia-desc": "Nossa IA atualmente em desenvolvimento. Muito em breve estará disponível para ajudá-lo em tudo o que você precisar. Nosso modelo será completo: terá visão, poderá falar, gerar texto e ouvir. Estamos treinando para ser o companheiro integral definitivo.",
        "learn-more": "Saber mais",
        "traspilador-desc": "Projetado para desenvolvedores. Um modelo de codificação capaz de converter projetos de uma linguagem para outra (exemplo: de JS para C++). Simplifique a migração de seus projetos e acelere seu fluxo de trabalho.",
        "explore-docs": "Explorar documentação",
        "footer-channels": "Canais",
        "footer-donations": "Doações",
        "footer-info": "Informação",
        "footer-products": "Nossos Produtos",
        "footer-donate-paypal": "Doar com PayPal",
        "footer-donate-info": "O que fazemos com suas doações?",
        "footer-privacy": "Política de Privacidade",
        "footer-license": "Licença",
        "footer-copyright": "© 2026 Carley Interactive Studio. Todos os direitos reservados.",
        "acc-modal-title": "Minha Conta",
        "field-email": "E-mail",
        "field-username": "Nome de Usuário",
        "btn-update": "Atualizar Perfil",
        "btn-logout": "Encerrar Sessão",
        "modal-hint": "Faça login para gerenciar seus projetos.",
        "btn-login": "Entrar",
        "btn-register": "Criar Conta",
        "login-title": "Entrar",
        "ph-email": "E-mail",
        "ph-pass": "Senha",
        "ph-pass-confirm": "Confirmar Senha",
        "btn-login-action": "Entrar",
        "register-title": "Criar Conta",
        "btn-register-action": "Registrar",
        "donations-modal-title": "O que fazemos com suas doações?",
        "donations-modal-desc": "Seu apoio nos permite contratar mais talentos, melhorar nossos servidores e acelerar o desenvolvimento de ferramentas gratuitas para a comunidade como o Creative Engine. Cada doação é investida diretamente na melhoria de nossas tecnologias.",
        "privacy-modal-title": "Privacidade",
        "privacy-modal-desc": "Seus dados estão seguros. Usamos apenas para melhorar sua experiência em nossa plataforma.",
        "license-modal-title": "Licença",
        "license-modal-desc": "Todos os nossos produtos são protegidos por leis de propriedade intelectual internacionais.",
        "ce-nav-tutorials": "Tutoriais",
        "ce-nav-solutions": "Soluções Rápidas",
        "ce-nav-docs": "Documentação",
        "ce-solutions-title": "Soluções Rápidas",
        "ce-solutions-placeholder": "Por enquanto, não há soluções rápidas, mas se você encontrar algum bug, por favor, denuncie. Assim começaremos a adicionar formas de resolvê-los.",
        "ce-tutorial-ui-title": "Aprenda a interface do Creative Engine",
        "ce-tutorial-ui-desc": "Aprenda a interface do Creative Engine para criar com facilidade. Você descobrirá tudo o que o motor tem no lançamento e para que serve cada ferramenta; assim você saberá melhor como criar o seu videogame.",
        "ce-tutorial-carl-title": "Como ativar o Carl",
        "ce-tutorial-carl-desc": "Aprenda como ativar o Carl, seu companheiro de desenvolvimento que o acompanhará no desenvolvimento de seus videogames.",
        "ce-tutorial-prog-title": "Como programar no Creative Engine",
        "ce-tutorial-prog-desc": "Aprenda a programar seus próprios videogames usando CES (Creative Engine Scripting) e outras ferramentas de codificação.",
        "tutorial-not-available": "Este tutorial ainda não está disponível, você quer ver nosso canal e outros vídeos?",
        // Vid Spri (PT)
        "vs-nav-tutorials": "Tutoriais",
        "ce-docs-leyes-title": "Guia de Componentes (Leis) - Creative Engine",
        "ce-docs-leyes-intro": "No Creative Engine, as Matérias (objetos) ganham vida através das Leis (componentes). Cada Lei adiciona uma funcionalidade específica, como gravidade, renderização de imagem ou lógica de IA. Este guia detalha o uso dos componentes tanto no Inspetor quanto nos Scripts (.ces) usando a sintaxe moderna (sem prefixos como this. ou motor.).",
        "ce-docs-core-title": "1. Componentes Base (Core)",
        "ce-docs-transform-name": "Transform (Transformação)",
        "ce-docs-transform-desc": "Define a posição, rotação e escala de um objeto no espaço 2D.",
        "ce-docs-transform-inspector": "Uso no Inspetor: Edite os valores X e Y para mover o objeto. Use os botões de inversão (Flip) para inverter a imagem.",
        "ce-docs-camera-name": "Camera (Câmera)",
        "ce-docs-camera-desc": "Define a área visível do jogo.",
        "ce-docs-camera-inspector": "Uso no Inspetor: Configure a cor de fundo, o zoom e a máscara de camadas (Culling Mask) para decidir quais objetos esta câmera vê.",
        "ce-docs-render-title": "2. Renderização e Visuais",
        "ce-docs-sprite-name": "SpriteRenderer (Renderizador de Sprite)",
        "ce-docs-sprite-desc": "Mostra uma imagem (.png, .jpg) ou um quadro de uma folha de sprites (.ceSprite).",
        "ce-docs-sprite-inspector": "Uso no Inspetor: Arraste uma imagem para o campo \"Source\". Você pode alterar a cor para tingir a imagem ou ajustar a opacidade.",
        "ce-docs-water-name": "Water (Água)",
        "ce-docs-water-desc": "Simulação física de fluidos baseada em partículas.",
        "ce-docs-water-inspector": "Uso no Inspetor: Define a largura e altura da área de água. Ajuste a densidade (flutuação) e viscosidade.",
        "ce-docs-video-name": "VideoPlayer (Reprodutor de Vídeo)",
        "ce-docs-video-desc": "Reproduz arquivos de vídeo no mundo ou na UI.",
        "ce-docs-video-inspector": "Uso no Inspetor: Suporta formatos .mp4 e .webm. Você pode ativar o loop e ajustar o volume.",
        "ce-docs-physics-title": "3. Físicas 2D",
        "ce-docs-rigidbody-name": "Rigidbody2D (Física)",
        "ce-docs-rigidbody-desc": "Permite que o objeto reaja à gravidade e colisões.",
        "ce-docs-rigidbody-inspector": "Uso no Inspetor: Altere o tipo de corpo para \"Dynamic\" para cair, ou \"Kinematic\" para movê-lo manualmente mas detectar colisões.",
        "ce-docs-collider-name": "BoxCollider2D / CircleCollider2D (Colisores)",
        "ce-docs-collider-desc": "Definem a forma física para os choques.",
        "ce-docs-collider-inspector": "Uso no Inspetor: Ajuste o tamanho ou raio. Se marcar \"Is Trigger\", o objeto não colidirá, mas detectará quando algo entrar em sua área.",
        "ce-docs-ai-title": "4. Inteligencia e Movimento",
        "ce-docs-basicai-name": "BasicAI (IA Básica)",
        "ce-docs-basicai-desc": "Comportamentos automáticos para NPCs e inimigos.",
        "ce-docs-basicai-modes": "Modos: Follow (Segue uma Matéria), Escape (Foge de um alvo), Wander (Caminha aleatoriamente).",
        "ce-docs-patrol-name": "Patrol (Patrulha)",
        "ce-docs-patrol-desc": "Move o objeto entre dois pontos.",
        "ce-docs-ui-title": "5. Interface de Usuário (UI)",
        "ce-docs-canvas-name": "Canvas (Tela)",
        "ce-docs-canvas-desc": "O contêiner principal para todos os elementos de interface.",
        "ce-docs-button-name": "Button (Botão)",
        "ce-docs-button-desc": "Detecta cliques do usuário.",
        "ce-docs-button-inspector": "Uso no Inspetor: Permite definir cores para os estados (Normal, Pressionado, Desativado) ou alterar sprites.",
        "ce-docs-uitext-name": "UIText (Texto UI)",
        "ce-docs-uitext-desc": "Mostra texto na tela com fontes personalizadas.",
        "ce-docs-anim-title": "6. Animação e Áudio",
        "ce-docs-animator-name": "AnimatorController (Controlador)",
        "ce-docs-animator-desc": "Gerencia estados de animação (Caminhar, Saltar, Parado).",
        "ce-docs-animator-inspector": "Uso no Inspetor: Requer um arquivo .ceanim. O \"Smart Mode\" anima automaticamente conforme o movimento.",
        "ce-docs-audio-name": "AudioSource (Fonte de Áudio)",
        "ce-docs-audio-desc": "Reproduz efeitos sonoros ou música.",
        "ce-docs-audio-inspector": "Uso no Inspetor: Suporta Áudio Espacial (o volume diminui se o objeto se afastar).",
        "ce-docs-others-title": "7. Outros Componentes",
        "ce-docs-others-raycast": "RaycastSource (Raio): Lança raios invisíveis para detectar paredes ou inimigos.",
        "ce-docs-others-particles": "ParticleSystem (Partículas): Cria efeitos de fogo, fumaça ou faíscas.",
        "ce-docs-others-parallax": "Parallax: Cria fundos infinitos com profundidade.",
        "ce-docs-others-light": "Light2D (Luzes): Ilumina sua cena com luzes pontuais ou focais.",
        "ce-docs-protip-title": "Pro-Tip de Scripting",
        "ce-docs-protip-desc": "Lembre-se que no Creative Engine, você pode acessar qualquer componente diretamente pelo seu nome. Não precisa usar prefixos.",
        "ce-docs-scripting": "Scripting",
        "vs-info-1": "O VidSpri foi criado pensando nos desenvolvedores novatos ou naqueles que querem criar seus jogos 2D mas não têm experiência desenhando cada quadro.",
        "vs-info-2": "Muitos recorreram à IA para gerar quadros para seus personagens, mas a IA também não consegue fazer bem este trabalho; ela não sabe como fazê-lo até que percebemos que a IA, ao gerar vídeo, faz muito melhor do que quando gera uma simples imagem com vários sprites.",
        "vs-info-3": "Tivemos a ideia de criar uma ferramenta que converte vídeos em folhas de sprites. Nossa ferramenta extrai quadros de vídeos e os converte em uma folha de sprites ou gera um vídeo para extrair quadros, conseguindo um melhor resultado.",
        "vs-info-4": "Para torná-lo mais completo, permitimos que ele gere som para seus jogos.",
        "vs-credits-main": "Créditos de Desenvolvimento e Assistência VidSpri é um projeto da Carley Interactive Studio. Este projeto foi desenvolvido com a assistência de Jules, um engenheiro de software de IA do Google.",
        "vs-credits-hf": "Agradecimentos Especiais à Hugging Face por fornecer hospedagem gratuita para nossos servidores através do Spaces.",
        "vs-credits-os": "Tecnologias e Bibliotecas de Código Aberto",
        "vs-tutorial-title": "Tutoriais",
        "vs-tutorial-desc": "Aprenda a usar o Vid Spri para seus projetos.",
        "vs-donate-1": "Seu apoio monetário nos ajudará a contratar desenvolvedores e pagar servidores para tornar o Vid Spri uma ferramenta gratuita.",
        "vs-os-python-desc": "A linguagem de programação que impulsiona todo o nosso backend.",
        "vs-os-docker-desc": "A plataforma de contêineres que nos permite implantar o servidor de forma confiável.",
        "vs-os-fastapi-desc": "Um framework web moderno e rápido para construir nossas APIs.",
        "vs-os-uvicorn-desc": "Um servidor ASGI ultrarrápido usado para executar o backend.",
        "vs-os-rembg-desc": "Poderosa biblioteca usada para remover o fundo das imagens de forma inteligente.",
        "vs-os-pillow-desc": "Biblioteca fundamental para manipulação de imagens em Python.",
        "vs-os-onnx-desc": "Motor de inferência de alto desempenho que alimenta o modelo rembg.",
        "vs-os-multipart-desc": "Biblioteca essencial para gestão de upload de arquivos no servidor.",
        "vs-os-sqlite-desc": "Motor de banco de dados usado para gerir a fila de processamento.",
        "vs-os-translate-desc": "O serviço que impulsiona a funcionalidade de tradução.",
        "vs-os-feather-desc": "Biblioteca de ícones de código aberto para a interface do usuário.",
        "vs-os-crop-desc": "Biblioteca JavaScript para funcionalidade de recorte de imagens no frontend.",
        "ce-nav-docs-leyes": "Componentes",
        "ce-nav-docs-scripting": "Scripting",
        "ce-nav-docs-libs": "Bibliotecas",
        "ce-nav-docs-carl": "Carl IA",
        "ce-nav-docs-terminal": "Terminal",
        "ce-nav-docs-editors": "Editores",
        "ce-nav-docs-advanced": "Avançado",
        "ce-nav-docs-config": "Configuração",
        "ce-docs-leyes-inspector": "Uso no Inspetor:",
        "ce-docs-leyes-scripting": "Scripting:",
        "ce-docs-transform-title": "Transform (Transformação)",
        "ce-docs-transform-ins": "Edite os valores X e Y para mover o objeto. Use os botões de inversão (Flip) para inverter a imagem.",
        "ce-docs-camera-title": "Camera (Câmera)",
        "ce-docs-camera-ins": "Configure a cor de fundo, o zoom e a máscara de camadas (Culling Mask).",
        "ce-docs-sprite-title": "SpriteRenderer (Renderizador de Sprite)",
        "ce-docs-sprite-ins": "Arraste uma imagem para o campo 'Source'. Você pode mudar a cor para tingir a imagem ou ajustar la opacidade.",
        "ce-docs-water-title": "Water (Água)",
        "ce-docs-water-ins": "Define a largura e altura da área de água. Ajuste a densidade (flutuação) e viscosidade.",
        "ce-docs-video-title": "VideoPlayer (Reprodutor de Vídeo)",
        "ce-docs-video-ins": "Suporta formatos .mp4 e .webm. Você pode ativar o loop e ajustar o volume.",
        "ce-docs-rigidbody-title": "Rigidbody2D (Física)",
        "ce-docs-rigidbody-ins": "Altere o tipo de corpo para 'Dynamic' para que caia, ou 'Kinematic' para movê-lo manualmente.",
        "ce-docs-colliders-title": "BoxCollider2D / CircleCollider2D",
        "ce-docs-colliders-desc": "Definem a forma física para os choques.",
        "ce-docs-colliders-ins": "Ajuste o tamanho ou raio. Se marcar 'Is Trigger', o objeto detectará sem colidir fisicamente.",
        "ce-docs-basicai-title": "BasicAI (IA Básica)",
        "ce-docs-patrol-title": "Patrol (Patrulha)",
        "ce-docs-canvas-title": "Canvas (Lienzo)",
        "ce-docs-button-title": "Button (Botão)",
        "ce-docs-uitext-title": "UIText (Texto UI)",
        "ce-docs-animator-title": "AnimatorController (Controlador)",
        "ce-docs-audio-title": "AudioSource (Fonte de Áudio)",
        "ce-docs-other-title": "7. Outros Componentes",
        "ce-docs-other-list": "RaycastSource (Raio), ParticleSystem (Partículas), Parallax, Light2D (Luzes).",
        "ce-docs-tip-title": "Pro-Tip de Scripting",
        "ce-docs-tip-desc": "Lembre-se que no Creative Engine, você pode acessar qualquer componente diretamente pelo seu nome. Você não precisa usar prefixos.",
        "ce-docs-scripting-title": "Guia Mestre de Scripting (CES)",
        "ce-docs-scripting-intro": "O Creative Engine utiliza CES (Creative Engine Script), uma linguagem poderosa baseada em JavaScript, mas simplificada para criadores de jogos.",
        "ce-docs-scripting-core-title": "Conceitos Fundamentais",
        "ce-docs-scripting-import": "Todo script deve começar com a instrução de conexão com o motor: ve motor;",
        "ce-docs-scripting-access": "Acesso Direto: Você NÃO precisa escrever this. ou mtr. para acessar os componentes.",
        "ce-docs-scripting-vars-title": "Variáveis Públicas (Inspetor)",
        "ce-docs-scripting-vars-desc": "Defina variáveis para que apareçam no Inspetor.",
        "ce-docs-scripting-input-title": "Entrada e Movimento",
        "ce-docs-scripting-functions-title": "Funções Especiais",
        "ce-docs-libs-title": "Instalação de Bibliotecas (.celib)",
        "ce-docs-libs-intro": "As bibliotecas estendem as funcionalidades do motor (ex: Multijogador, Inventários).",
        "ce-docs-libs-step-1": "Baixe o arquivo .celib.",
        "ce-docs-libs-step-2": "Mova-o para a pasta /lib do seu projeto.",
        "ce-docs-libs-step-3": "O motor irá carregá-lo automaticamente ao iniciar.",
        "ce-docs-carl-title": "Execução com Carl IA",
        "ce-docs-carl-intro": "O Carl pode automatizar tarefas complexas usando IA.",
        "ce-docs-carl-modes": "Modos de Execução:",
        "ce-docs-carl-mode-1": "Modo Comando: Executa ações imediatas no editor.",
        "ce-docs-carl-mode-2": "Modo Scripting: Ajuda a escrever e depurar código CES.",
        "ce-docs-terminal-title": "Guia do Terminal",
        "ce-docs-terminal-intro": "O Terminal é uma ferramenta avançada para interagir com o motor através de comandos de texto.",
        "ce-docs-terminal-activate": "Como Ativar o Terminal",
        "ce-docs-terminal-fs-title": "1. Comandos do Sistema de Arquivos",
        "ce-docs-terminal-scene-title": "2. Comandos de Cena",
        "ce-docs-advanced-title": "Guia Avançado: Projetos, Cenas e Build",
        "ce-docs-advanced-intro": "Este guia cobre os aspectos fundamentais da gestão de ativos, design de níveis e publicação final do jogo.",
        "ce-docs-advanced-struct-title": "1. Estrutura do Projeto",
        "ce-docs-advanced-scenes-title": "2. Gestão de Cenas (.ceScene)",
        "ce-docs-advanced-build-title": "3. O Sistema de Build (Publicación)",
        "ce-docs-editors-title": "Guia de Editores Visuais",
        "ce-docs-editors-intro": "O Creative Engine inclui uma suíte de ferramentas visuais para gerir gráficos, animações e níveis de forma intuitiva.",
        "ce-docs-editors-sprite-title": "1. Editor de Sprites (Sprite Slicer)",
        "ce-docs-editors-anim-title": "2. Editor de Animações (.cea)",
        "ce-docs-editors-tilemap-title": "3. Editor de Tilemap",
        "ce-docs-config-title": "Guia de Configuração e Atmosfera",
        "ce-docs-config-intro": "Aprenda como personalizar seu fluxo de trabalho e configurar os parâmetros técnicos do seu projeto.",
        "ce-docs-config-project-title": "1. Configuração do Projeto",
        "ce-docs-config-ambient-title": "2. Controle de Atmosfera",
        "ce-docs-carl-keys": "Configure sua chave em Editar > Preferências > IA. Suportamos Google Gemini (Grátis), OpenAI e Anthropic.",
        "ce-docs-carl-skill-1": "\"Crie um objeto chamado Jogador com SpriteRenderer.\"",
        "ce-docs-carl-skill-2": "\"Crie um script que mova o jogador com as setas.\"",
        "ce-docs-terminal-ls": "ls: Listar arquivos.",
        "ce-docs-terminal-cd": "cd <pasta>: Mudar de pasta.",
        "ce-docs-terminal-clear": "clear: Limpar terminal.",
        "ce-docs-terminal-act-1": "Janela > Terminal",
        "ce-docs-terminal-act-2": "Painel Inferior > Aba Terminal.",
        "ce-docs-advanced-struct-1": "/Assets: Imagens, sons, scripts.",
        "ce-docs-advanced-struct-2": "/lib: Bibliotecas (.celib).",
        "ce-docs-advanced-struct-3": "project.ceconfig: Configuração técnica.",
        "ce-docs-advanced-scenes-desc": "Use Ctrl + S para salvar. As cenas (.ceScene) contêm todos os objetos e luzes.",
        "ce-docs-advanced-build-desc": "Gera um pacote web independente (.zip) pronto para hospedagem.",
        "ce-docs-editors-sprite-desc": "Recorte imagens grandes em múltiplos sprites pequenos.",
        "ce-docs-editors-anim-desc": "Crie sequências (.cea) usando uma linha do tempo.",
        "ce-docs-editors-tilemap-desc": "Desenhe níveis baseados em grade com pincéis e camadas.",
        "ce-docs-config-project-desc": "Gerencia Sorting Layers, Collision Layers e Tags.",
        "ce-docs-config-ambient-desc": "Ciclo Dia/Noite, filtros de cor e luzes ambiente."
    },
    },
